export type AdminData = {
    twitter?: string;
    telegram?: string;
    instagram?: string;
    discord?: string;
    favicon?: string;
    pageTitle: string;
    sidebarTitle: string;
    mainTitle: string;
    subTitle: string;
    featuredCardTitle: string;
    featuredCardDescription: string;
    featuredCardTitle1: string;
    featuredCardDescription1: string;
    featuredCardTitle2: string;
    featuredCardDescription2: string;
    siteMaintainanceMode: boolean;
    webhooksMaintainanceMode: boolean;
    allowSignup: boolean;
    // inviteCodes?: string[];
};