import { useEffect, useState } from "react";
import type { AppProps } from "next/app";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import App from "@/components/App";
import { getPageData, getSidebarTitle, getSocialLinks } from "@/utils/api";
import "../styles/globals.css"; // Import global styles
import { AdminData } from "@/types/admin-data";

export default function MyApp({ Component, pageProps }: AppProps) {
  const [sidebarTitle, setSidebarTitle] = useState("");
  const [socialLinks, setSocialLinks] = useState({});
  const [pageData, setPageData] = useState<Partial<AdminData>>({});

  useEffect(() => {
    async function fetchData() {
      try {
        const result = await getSocialLinks("");
        const data = await getSidebarTitle("");
        const pagedata = await getPageData();
        setPageData(pagedata)
        setSidebarTitle(data.sidebarTitle);
        setSocialLinks(result?.data || {});
      } catch (error) {
        console.error("Failed to fetch sidebar/social data:", error);
      }
    }

    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>{pageData.pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        {pageData.favicon && (
          <>
            <link rel="icon" href={pageData.favicon} />
            <link rel="shortcut icon" href={pageData.favicon} />
          </>
        )}
      </Head>
      <main className={`antialiased`}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
          theme="colored"
        />
        <App socialLinks={socialLinks} sidebarTitle={sidebarTitle}>
          <Component {...pageProps} pageTitle={pageData.pageTitle} />
        </App>
      </main>
    </>
  );
}
