import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import App from "./App";
import { getSidebarTitle, getSocialLinks } from "@/utils/api";
import { ToastContainer } from "react-toastify";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const jwtToken = (await cookies()).get('jwtToken')?.value;
  const result = await getSocialLinks(jwtToken || '');
  const data = await getSidebarTitle(jwtToken || '');

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          closeOnClick={true}
          pauseOnHover={true}
          draggable={true}
          theme='colored'
        />
        <App socialLinks={result ? result.data : {}} sidebarTitle={data.sidebarTitle}>{children}</App>
      </body>
    </html>
  );
}
